application/__init__.py
from flask import Flask

from application.main.routes import main

from .extensions import mongo

import os

def createapp():
    user = os.getenv("MONGO_USER")
    password = os.getenv("MONGO_PASSWORD")
    host = os.getenv("MONGO_HOST")
    db = os.getenv("MONGO_DB")
    app = Flask(__name__)

    app.config["MONGO_URI"] = f"mongodb+srv://{user}:{password}@{host}/{db}?retryWrites=true&w=majority&appName=Recycle"
    mongo.init_app(app)

    app.register_blueprint(main)
    return app

application/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from bson.objectid import ObjectId

from ..extensions import mongo

main = Blueprint('main',__name__)



@main.route('/')
def index():
    todos_collection = mongo.db.todos
    todos = todos_collection.find()
    return render_template('index.html', todos = todos)

@main.route('/add_todo', methods=['POST'])
def add_todo():
    todos_collection = mongo.db.todos
    todo_item = request.form.get('add_todo')
    todos_collection.insert_one({'text': todo_item, 'complete':False})
    return redirect(url_for('main.index'))

@main.route('/complete_todo/<oid>')
def complete_todo(oid):
    todos_collection = mongo.db.todos
    todos_collection.update_one({"_id": ObjectId(oid)}, {"$set": {"complete": True}})

    return redirect(url_for('main.index'))

@main.route('/delete_completed')
def delete_completed():
    todos_collection = mongo.db.todos
    todos_collection.delete_many({'complete':True})
    return redirect(url_for('main.index'))

@main.route('/delete_all')
def delete_all():
    todos_collection = mongo.db.todos
    todos_collection.delete_many({})
    return redirect(url_for('main.index'))

@main.route('/sign_in')
def sign_in():
    
    return render_template('login.html')

application/templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>ToDo App</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='flatly.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]action=>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row">
				<div class="col-lg-4 col-lg-offset-4" id="content">
					<h2>WHAT DO YOU WANT TO DO TODAY?</h2>
					
					<form action="{{ url_for('main.add_todo')}}" method="POST"  role="form">
					
						<div class="form-group">
							<div class="input-group">
							  <input name="add_todo" type="text" class="form-control" placeholder="Enter todo e.g. Delete junk files" aria-label="Todo" aria-describedby="add-btn">
							  <span class="input-group-btn">
								  <button type="submit" class="btn btn-default" id="add-btn">ADD</button>
							  </span>
							</div>
						</div>
					</form>

					<div class="row t10">
						<div class="col-lg-12">
							<div class="btn-toolbar">
								<div class="btn-group">
									<a type="button" href="{{ url_for('main.delete_completed')}}" class="btn btn-warning">
										DELETE COMPLETED
									</a>
								</div>
								<div class="btn-group">
									<a type="button" href="{{ url_for('main.delete_all')}}" class="btn btn-warning">
										DELETE ALL
									</a>
								</div>
							</div>
						</div>
					</div>

					<ul class="list-group t20">
						{% for todo in todos %}
						<a href="{{ url_for('main.complete_todo',oid = todo._id)}}">
							<li class="list-group-item {% if todo.complete %}todo-completed{% endif %}">
								{{ todo.text }}
							</li>
						</a>
						{% endfor %}
					</ul>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2020 <strong>ToDo App</strong>
					</div>
				</div>
			</footer>
		</div>
	</body>
</html>

application/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form>
        <div class="mb-3">
          <label for="inputEmail" class="form-label">Email address</label>
          <input name="email" type="email" class="form-control" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</body>
</html>